[2025-04-20T05:17:04.224+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spacex_ml_training_pipeline.train_model manual__2025-04-20T05:17:03.224713+00:00 [queued]>
[2025-04-20T05:17:04.230+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spacex_ml_training_pipeline.train_model manual__2025-04-20T05:17:03.224713+00:00 [queued]>
[2025-04-20T05:17:04.230+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2025-04-20T05:17:04.238+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): train_model> on 2025-04-20 05:17:03.224713+00:00
[2025-04-20T05:17:04.242+0000] {standard_task_runner.py:57} INFO - Started process 200 to run task
[2025-04-20T05:17:04.249+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'spacex_ml_training_pipeline', 'train_model', 'manual__2025-04-20T05:17:03.224713+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/spacex_training_dag.py', '--cfg-path', '/tmp/tmp97g1fdk6']
[2025-04-20T05:17:04.258+0000] {standard_task_runner.py:85} INFO - Job 3: Subtask train_model
[2025-04-20T05:17:04.278+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-20T05:17:04.306+0000] {task_command.py:415} INFO - Running <TaskInstance: spacex_ml_training_pipeline.train_model manual__2025-04-20T05:17:03.224713+00:00 [running]> on host d19d881c2823
[2025-04-20T05:17:04.364+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='gaurav' AIRFLOW_CTX_DAG_ID='spacex_ml_training_pipeline' AIRFLOW_CTX_TASK_ID='train_model' AIRFLOW_CTX_EXECUTION_DATE='2025-04-20T05:17:03.224713+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-20T05:17:03.224713+00:00'
[2025-04-20T05:17:04.366+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-04-20T05:17:04.369+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /opt/***/project/train.py']
[2025-04-20T05:17:04.379+0000] {subprocess.py:86} INFO - Output:
[2025-04-20T05:17:06.491+0000] {subprocess.py:93} INFO - 2025/04/20 05:17:06 WARNING mlflow.utils.git_utils: Failed to import Git (the Git executable is probably not on your PATH), so Git SHA is not available. Error: Failed to initialize: Bad git executable.
[2025-04-20T05:17:06.492+0000] {subprocess.py:93} INFO - The git executable must be specified in one of the following ways:
[2025-04-20T05:17:06.492+0000] {subprocess.py:93} INFO -     - be included in your $PATH
[2025-04-20T05:17:06.492+0000] {subprocess.py:93} INFO -     - be set via $GIT_PYTHON_GIT_EXECUTABLE
[2025-04-20T05:17:06.492+0000] {subprocess.py:93} INFO -     - explicitly set via git.refresh(<full-path-to-git-executable>)
[2025-04-20T05:17:06.493+0000] {subprocess.py:93} INFO - 
[2025-04-20T05:17:06.493+0000] {subprocess.py:93} INFO - All git commands will error until this is rectified.
[2025-04-20T05:17:06.493+0000] {subprocess.py:93} INFO - 
[2025-04-20T05:17:06.493+0000] {subprocess.py:93} INFO - This initial message can be silenced or aggravated in the future by setting the
[2025-04-20T05:17:06.493+0000] {subprocess.py:93} INFO - $GIT_PYTHON_REFRESH environment variable. Use one of the following values:
[2025-04-20T05:17:06.494+0000] {subprocess.py:93} INFO -     - quiet|q|silence|s|silent|none|n|0: for no message or exception
[2025-04-20T05:17:06.494+0000] {subprocess.py:93} INFO -     - warn|w|warning|log|l|1: for a warning message (logging level CRITICAL, displayed by default)
[2025-04-20T05:17:06.494+0000] {subprocess.py:93} INFO -     - error|e|exception|raise|r|2: for a raised exception
[2025-04-20T05:17:06.494+0000] {subprocess.py:93} INFO - 
[2025-04-20T05:17:06.495+0000] {subprocess.py:93} INFO - Example:
[2025-04-20T05:17:06.495+0000] {subprocess.py:93} INFO -     export GIT_PYTHON_REFRESH=quiet
[2025-04-20T05:17:06.495+0000] {subprocess.py:93} INFO - 
[2025-04-20T05:17:08.654+0000] {subprocess.py:93} INFO - 2025/04/20 05:17:08 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
[2025-04-20T05:17:11.810+0000] {subprocess.py:93} INFO - 2025/04/20 05:17:11 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
[2025-04-20T05:17:16.612+0000] {subprocess.py:93} INFO - 2025/04/20 05:17:16 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
[2025-04-20T05:17:19.945+0000] {subprocess.py:93} INFO - 2025/04/20 05:17:19 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
[2025-04-20T05:17:19.968+0000] {subprocess.py:93} INFO - Training LogisticRegression...
[2025-04-20T05:17:19.970+0000] {subprocess.py:93} INFO - → LogisticRegression logged to MLflow.
[2025-04-20T05:17:19.970+0000] {subprocess.py:93} INFO - Training SVM...
[2025-04-20T05:17:19.970+0000] {subprocess.py:93} INFO - → SVM logged to MLflow.
[2025-04-20T05:17:19.972+0000] {subprocess.py:93} INFO - Training DecisionTree...
[2025-04-20T05:17:19.973+0000] {subprocess.py:93} INFO - → DecisionTree logged to MLflow.
[2025-04-20T05:17:19.973+0000] {subprocess.py:93} INFO - Training KNN...
[2025-04-20T05:17:19.974+0000] {subprocess.py:93} INFO - → KNN logged to MLflow.
[2025-04-20T05:17:19.974+0000] {subprocess.py:93} INFO - Best model saved: LogisticRegression
[2025-04-20T05:17:20.339+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-04-20T05:17:20.383+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=spacex_ml_training_pipeline, task_id=train_model, execution_date=20250420T051703, start_date=20250420T051704, end_date=20250420T051720
[2025-04-20T05:17:20.428+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-04-20T05:17:20.441+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
